const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('widget', {
  getInitial: () => ipcRenderer.invoke('get-initial'),
  setColor: (c) => ipcRenderer.send('set-color', c),
  setGlass: (g) => ipcRenderer.send('set-glass', g),
  onOpenColor: (cb) => ipcRenderer.on('open-color', () => cb()),
  setPref: (p) => ipcRenderer.send('set-pref', p),
  setTrayIcon: (d) => ipcRenderer.send('tray-icon', d),
  onToggleCollapse: (cb) => ipcRenderer.on('toggle-collapse', () => cb()),
  onLocked: (cb) => ipcRenderer.on('locked', (_e, v) => cb(v)),
  onRefit: (cb) => ipcRenderer.on('refit', () => cb()),
  setUiState: (st) => ipcRenderer.send('ui-state', st),
  onHover: (cb) => ipcRenderer.on('hover', (_e, v) => cb(v)),
  onLayout: (cb) => ipcRenderer.on('layout', (_e, v) => cb(v)),
  onGhost: (cb) => ipcRenderer.on('ghost', (_e, v) => cb(v)),
  onDock: (cb) => ipcRenderer.on('dock', (_e, v) => cb(v)),
  onAnchor: (cb) => ipcRenderer.on('anchor', (_e, v) => cb(v)),
  onPaused: (cb) => ipcRenderer.on('paused', (_e, v) => cb(v)),
  onIcon: (cb) => ipcRenderer.on('icon', (_e, v) => cb(v)),
  onPets: (cb) => ipcRenderer.on('pets', (_e, v) => cb(v)),
  setGhostInteractive: (v) => ipcRenderer.send('ghost-interactive', v),
  onGhostInteractive: (cb) => ipcRenderer.on('ghost-interactive', (_e, v) => cb(v)),
  onLowfx: (cb) => ipcRenderer.on('lowfx', (_e, v) => cb(v)),
  onFont: (cb) => ipcRenderer.on('font', (_e, f) => cb(f)),
  onUsage: (cb) => ipcRenderer.on('usage', (_e, p) => cb(p)),
  refresh: () => ipcRenderer.send('refresh'),
  login: () => ipcRenderer.send('login'),
  setSessionKey: (k) => ipcRenderer.invoke('set-session-key', k),
  hide: () => ipcRenderer.send('hide'),
  menu: () => ipcRenderer.send('menu'),
  openUsage: () => ipcRenderer.send('open-usage'),
  resize: (h) => ipcRenderer.send('resize', h),
  readClipboardKey: () => ipcRenderer.invoke('read-clipboard-key'),
  openClaudeBrowser: () => ipcRenderer.send('open-claude-browser'),
});
